### ISSUE TITLE
Consider listing gotime podcast on stitcher service

### ISSUE THREAD

**Issue by dhoucgitter** [GoTimeFM/ping#19]
Awesome show folks!
Would you consider listing the goTimeFM podcast on the Stitcher service? 
It makes it convenient to subscribe to content, auto-download new episodes and listen offline on Android devices.
I see that the changelog podcast is listed there, but goTimeFM does not appear to be.
See http://www.stitcher.com/content-providers.php for more info.

Thanks for all the great go information you guys are putting out there!

**Comment by carlisia** [comment]
@adamstac / @jerodsanto this is for you.

@dhoucgitter glad you are liking the show and thanks for the ping!

**Comment by jerodsanto** [comment]
Howdy, @dhoucgitter! We aren't huge fans of Stitcher because of how they treat content creators. Stitcher will:

1. Re-host our files, removing our ability to track downloads
2. Re-sample our files, possibly reducing sound quality
3. Insert their own ads in to our shows

For these reasons, we aren't interested in working with them at this time. The Changelog is in there because of a deal between 5by5 (our previous network) and Stitcher.

Thankfully, there are plenty of other great way to subscribe on Android!

http://www.subscribeonandroid.com/changelog.com/gotime/feed

Thanks for listening! 💚

**Comment by dhoucgitter** [comment]
Hi Jerod,

Thanks for your reply.
I noticed the suggestions for other android podcast players on your site. I
have switched to using Player FM and it's working great. Thanks for all
your efforts in producing such great content with high quality audio.

David
