### ISSUE TITLE
slack channel incorrect on livestream page

### ISSUE THREAD

**Issue by pfhawkins** [GoTimeFM/ping#29]
https://changelog.com/live has this: 
<img width="398" alt="live_and_upcoming_shows___changelog_" src="https://cloud.githubusercontent.com/assets/5287/24265680/ba0fdb64-0fda-11e7-962c-dc4d83755006.png">

But the actual slack channel is named #gotimefm

This is probably a low-priority issue, because searching for the former channel will surface the latter.

**Comment by plod** [comment]
Isnt this because on the changelog slack it is #gotime but on the gopher slack it is #gotimefm

**Comment by jerodsanto** [comment]
Yes, that is correct. Go Time Live existed before Changelog had free community. Since they already had a vibrant Slack, that is where the chat started for that show. We have the two rooms linked up using [Slackline](https://slackline.io), so either one works, but the CMS is built around Changelog Slack since other live shows only exist in there.

The easiest fix (IMHO) is to rename the room in Gophers Slack from #gotimefm to #gotime so it matches. But like @pfhawkins said, it's a small issue since you can find the channel if you're searching in Gophers Slack for it.

**Comment by jerodsanto** [comment]
Closing this as I think we're at a stand still on it. Thanks for the heads up @pfhawkins
