### ISSUE TITLE
Suggestion for end-of-show question

### ISSUE THREAD

**Issue by eli4d** [GoTimeFM/ping#5]
Dear Go Time hosts,

I've been enjoying the episodes that you guys have published so far - keep up the great work!

I'm very interested in learning Go but my last foray into it didn't go that far (pun not intended).  Many shows have a "picks" type of question for guests and for the hosts.  I was wondering if perhaps you can consider putting an end-of-show question related to how to best learn Go.

Here is the type of question that I'm suggesting:

Question for guest(s):

"If you were to go back to the beginning when you were learning Go - what is that one concept or the 'one thing' that you wish you knew?  In other words, knowing what you know now - what would you tell yourself as that beginner Go developer - the thing that would accelerate your learning?  This can be a core concept, feature, etc... .  If you're an experienced programmer, then what was the one thing that helped you transform your thinking into a 'Go mindset' that made Go click for you."

Question for hosts when there's no guest:

- Any new beginner type of resources?
- Any 'first core concepts' that hosts want to point out (or that have been clarified by a great blog post, sample project etc...)?
- Any decent roadmap to learning Go that they've come across.

Thanks for 'listening' to my suggestion :-).

Keep up the great work.

eli4d

**Comment by carlisia** [comment]
@eli4d I loved your suggestion. As a relative newcomer to Go, I've been trying to weave in my perspectives when I think it's useful, exactly for the reasons you state. 

I'll have the Go Time team look at your suggestion and see if we can do something more intentional.

**Comment by eli4d** [comment]
Hi Carlisia - thanks for responding!

**Comment by carlisia** [comment]
Hey @eli4d,

It turns out that we don't think having this as part of every show would be feasible, as we think it would get repetitive really quickly. We do think the questions are awesome to ask once in a while, and so I wrote them down on our trello board. Also, feel free to ask them during the live show if you are around the #gotimefm channel on Gophers slack if there's a particular guest you'd like to hear the answers from.

Also, there seems to be heavy agreement that there is no clear path for newcomers and, more importantly, that we need to fix that. If you were not at GopherCon this year I highly encourage you watch Katrina Owen's talk. Also, this is a great post, pasting here in case you haven't seen it: https://medium.com/@mattetti/go-is-for-everyone-b4f84be04c43#.paisuglt9

Closing this issue, thanks!
